### ISSUE TITLE
python-api is not compatible with Python 3

### ISSUE THREAD

**Issue by sdenel** [Koheron/laser-development-kit#15]
Python 3 will replace Python 2 in Ubuntu 16.04 [(source)](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-16.04-Python-3-Hopes)

python-api is not compatible with Python 3. Only minor changes are necessary. As far as I can see, you mainly have to change the way you use print, that is no more a statement but a function. From [What’s New In Python 3.0](https://docs.python.org/3.0/whatsnew/3.0.html):

    Old: print "The answer is", 2*2
    New: print("The answer is", 2*2)

**Comment by jeanminet** [comment]
Thank you !
