### ISSUE TITLE
Doppler Lidar spectrum animated

### ISSUE THREAD

**Issue by tvanderbruggen** [Koheron/laser-development-kit#25]
![doppler_spectrum](https://cloud.githubusercontent.com/assets/7926718/11698739/97ee912e-9ec0-11e5-8878-7bdfb48be726.gif)

**Comment by jeanminet** [comment]
![Koheron coherent doppler lidar velocimeter](https://cloud.githubusercontent.com/assets/1735094/11727699/c4c9ab1e-9f85-11e5-9e94-c95089464c42.gif)
