### ISSUE TITLE
http connexion failure in spectrum mode

### ISSUE THREAD

**Issue by llombard** [Koheron/laser-development-kit#49]
in the file examples/spectrum_analyzer.py I had to change:
`http = HTTPInterface(host)`
`http.install_instrument('spectrum')`

to 

`ssh = ZynqSSH(host, 'changeme')`
`ssh.unzip_app()`
`ssh.install_instrument('spectrum')`

otherwise it raises an error.

**Comment by tvanderbruggen** [comment]
Thanks for the feedback.

Could you post the log of error ?

**Comment by llombard** [comment]
![screenshot from 2016-03-03 19 05 29](https://cloud.githubusercontent.com/assets/13920358/13502756/917ecc34-e16c-11e5-88f2-235b21f412f4.png)

**Comment by tvanderbruggen** [comment]
Thanks. 

Looks like the HTTP app is not launched. Do you have access to the WEB interface when you type the IP address of the board into your browser ?

**Comment by llombard** [comment]
No I don't. The browser does not find the server.

**Comment by jeanminet** [comment]
@llombard Thanks for the fix 0e8e9c2 
But it does not fix the fact that your web app does not launch.
What is the version of your SD card image ?

**Comment by llombard** [comment]
i used oscillo-d199eb1.img

**Comment by tvanderbruggen** [comment]
I just did a fresh burn of a SD card with oscillo-d199eb1.img and I get the Web page running.

Could you open a SSH shell on your board and post the result of the following commands:
```
ls -l /usr/local/instruments/
cat /usr/local/instruments/.instruments
cat /var/log/flask-uwsgi/flask-uwsgi.log
```

Thank you.

**Comment by llombard** [comment]
```
root@koheron:~# ls -l /usr/local/instruments/
total 672
drwxr-xr-x 2 root root   4096 Feb 28 02:22 backup
-rw-r--r-- 1 root root 257964 Feb 28 02:22 oscillo-d199eb1.zip
-rw-r--r-- 1 root root 425356 Feb 28 02:22 spectrum-d199eb1.zip
root@koheron:~# cat /usr/local/instruments/.instruments
cat: /usr/local/instruments/.instruments: No such file or directory
root@koheron:~# cat /var/log/flask-uwsgi/flask-uwsgi.log
cat: /var/log/flask-uwsgi/flask-uwsgi.log: No such file or directory
```

**Comment by tvanderbruggen** [comment]
Thanks,

Looks like the app didn't even try to launch. This is usually due to a failure when `eth0` gets up since the HTTP interface is launched at post-up.

Can you show me the content of this log:
```
cat /var/log/syslog | grep KServer
```
Also what do you have after running:
```
bash /usr/local/flask/nginx.sh
```
Is the WEB page available after that ?
